version: '0.1'
services:
  mongo:
    image: mongo:6.0
    restart: always
    env_file:
      - RestAPI/.env_prod
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  app:
    build: 
      context: .
    env_file:
      - RestAPI/.env_prod
    container_name: DEEPHACK_AGENTS
    command: "gunicorn main:app -w 9 -k uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - mongo